name: Pull Request on Branch Push

on: [ push ]

env:
  GH_TOKEN: ${{ github.token }}
      
jobs:
  auto-pull-request:
    name: Create New PR From Branch
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
          
      - name: Create PR
        run: gh pr create --title "${{ github.head_ref }}" -T "PULL_REQUEST_TEMPLATE.md"
