name: Pull Request on Branch Push

on: [ push ]

env:
  GH_TOKEN: ${{ github.token }}
      
jobs:
  auto-pull-request:
    name: Create New PR From Branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
          
      - name: Fetch PR template
        uses: actions/checkout@v4
        with:
          repository: pahukama/.github
          path: .github-org
          ref: main
          
      - name: Create PR
        run: gh pr create --title "${{ github.head_ref }}" --body-file ".github-org/.github/PULL_REQUEST_TEMPLATE.md"
        continue-on-error: true
