# This workflow will automatically create a new pull request when a new branch is pushed and validated
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Validate Branch & Open PR

on: [ push ]

env:
  GH_TOKEN: ${{ github.token }}
  BRANCH_NAME: ${GITHUB_REF#refs/heads/}
      
jobs:
  validate-branch:
    name: Validate Branch
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch name
        if: ${{ startsWith( github.ref_name, 'feature') || startsWith( github.ref_name, 'fix') || startsWith( github.ref_name, 'task') || startsWith( github.ref_name, 'refactor') || startsWith( github.ref_name, 'revert') }}$
        run: |
          echo github.ref_name
          echo "Invalid branch name, must start with: feature, fix, task, refactor, or revert."
          exit 1
              
  create-pull-request:
    name: Create New PR From Branch
    needs: validate-branch # This causes the step to abort if validation failed
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
          
      - name: Fetch PR template
        uses: actions/checkout@v4
        with:
          repository: pahukama/.github
          path: .github-org
          ref: main
          
      - name: Create PR
        run: gh pr create --title "${{ github.head_ref }}" --body-file ".github-org/.github/PULL_REQUEST_TEMPLATE.md"
        continue-on-error: true
