# This workflow will automatically create a new pull request when a new branch is pushed and validated
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Branch Ops

on: 
  create:
    branches: [ "*" ]
  pull_request: 
    types: [edited]
    
env:
  GH_TOKEN: ${{ github.token }}
  BRANCH_NAME: ${GITHUB_REF#refs/heads/}
      
jobs:
  validate-branch:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      
      - name: Validate branch name
        if: |
          !startsWith(steps.extract_branch.outputs.branch,'feature') && 
          !startsWith(steps.extract_branch.outputs.branch,'fix') &&
          !startsWith(steps.extract_branch.outputs.branch,'task') &&
          !startsWith(steps.extract_branch.outputs.branch,'refactor') &&
          !startsWith(steps.extract_branch.outputs.branch,'revert')
        run: |
          echo ${{ github.ref_name }}
          echo "Invalid branch name, must start with: feature, fix, task, refactor, or revert."
          exit 1
              
  create-pull-request-and-link-issues:
    name: Create Draft PR & Link Issue(s)
    needs: validate-branch # This causes the step to abort if validation failed
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
          
      - name: Fetch PR template
        uses: actions/checkout@v4
        with:
          repository: pahukama/.github
          path: .github-org
          ref: main
          
      - name: Create PR
        run: gh pr create --title "${{ needs.validate-branch.outputs.branch_name }}" --body-file ".github-org/.github/PULL_REQUEST_TEMPLATE.md" --draft
        continue-on-error: true

      - name: Linke Issue Attempt 1
        uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          header: '## Related Issues(s)'
          branch-prefix: 'issue-' # required

      - name: Linke Issue Attempt 2
        uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          header: '## Related Issues(s)'
          branch-prefix: '#' # required
