# This workflow will automatically create a new pull request when a new branch is pushed and validated
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Branch-OPS

on:
  create:
    branches:
      - '*'
  pull_request:
    types: [ edited ]
  pull_request_review:
    types: [edited, submitted]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  validate-branch:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
      
    steps:
      - name: Get Branch Name
        id: get_branch_name
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Validate Branch Name
        if: | 
          !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'feature') 
          && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'fix')
          && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'task')
          && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'revert')
          && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'refactor')
        run: |
          echo "Error: Branch name '${{ steps.get_branch_name.outputs.BRANCH_NAME }}' does not follow conventions (e.g., 'feature/', 'fix/', 'task/')."
          exit 1

  create-pull-request-and-link-issues:
    name: Create Draft PR
    needs: validate-branch # This causes the step to abort if validation failed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Fetch PR template
        uses: actions/checkout@v4
        with:
          repository: pahukama/.github
          path: .github-org
          ref: main
          
      - name: Create Pull Request
        continue-on-error: true
        run: | 
          echo "Branch name validated, creating pull request..."
          gh pr create --title "${{ needs.validate-branch.outputs.branch_name }}" --body-file ".github-org/.github/PULL_REQUEST_TEMPLATE.md" -d
