# This workflow will automatically create a new pull request when a new branch is pushed and validated
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
on:
  create:
    branches:
      - '*'
  pull_request:
    types: [ edited ]

jobs:
  validate-and-pr:
    name: Validate Branch Name and Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        id: get_branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Validate Branch Name
        if: | 
          ${{ !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'feature/') 
              && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'fix/' 
              && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'task/'
              && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'revert/'
              && !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'refactor/')
            }}
        run: |
          echo "Error: Branch name '${{ steps.get_branch_name.outputs.BRANCH_NAME }}' does not follow conventions (e.g., 'feature/' or 'bugfix/')."
          exit 1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Initial commit for new branch"
          title: "Draft PR for ${{ steps.get_branch_name.outputs.BRANCH_NAME }}"
          body: "This is a draft PR for the newly created branch. Please add details and mark ready for review when complete."
          branch: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
          base: main
          draft: true

      - name: Linke Issue Attempt 1
        uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          header: '## Related Issues(s)'
          branch-prefix: 'issue-' # required

      - name: Linke Issue Attempt 2
        uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          header: '## Related Issues(s)'
          branch-prefix: '#' # required
