# This workflow will do a clean installation of node dependencies, cache/restore them, and lint the project.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: PR Sanity Checks  # name of the action (displayed in the github interface)

on:  # on all pull requests
  pull_request: 
    types: [opened, edited, synchronize, reopened]
    
jobs:
  auto-assign-and-label:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: tchibanda24 # if draft, assigned when draft is released
          
  validate-title:
    name: Validate PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feature|fix|task|refactor|revert){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)' # Conventional grouping style commit
          allowed_prefixes: 'feature,fix,task,refactor,revert,test' # title should start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 15 # Min length of the title
          max_length: 72 # Max length of the title
          verbal_description: 'PR title must match conventional format, ex. {feature,fix,task,refactor,revert,test}(ISSUE-#): my pull request' # Verbal description of the regex rule
          github_token: ${{ github.token }} # Default: ${{ github.token }}
