name: Workflow Publisher
on:
 push:
   branches: [ 'main' ]
   paths:
   - 'workflow-templates/**'
   
jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [ 'pahukama-webos' , 'pahukama-dashboard' ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          persist-credentials: false

                
      - name: Git PAT 
        run: git config --global url.https://tchibanda24@github.com/.insteadOf https://github.com/
          
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}.git
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.RW_REPO }}
          ref: main
          
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/workflow-templates/* .github/workflows/
        working-directory: ./${{ matrix.target_repo }}
        
      - name: Publish workflows
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Github Agent | Workflows has updated"
          git push
        working-directory: ./${{ matrix.target_repo }}
