name: Workflow Publisher
on:
 push:
   branches: [ 'main' ]
   paths:
   - 'templates/**'
   
jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [ 'pahukama-webos' , 'pahukama-dashboard', 'pahukama-serverless' ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.RW_REPO }}
          ref: main
          
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../templates/workflows/* .github/workflows/
          cp ../templates/labeler.yml .github/
          cp ../templates/CODEOWNERS .github/
        working-directory: ./${{ matrix.target_repo }}
        
      - name: Publish workflows
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Github Agent | Workflows has updated"
          git push
        working-directory: ./${{ matrix.target_repo }}
        
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: ../templates/labels.yml
